### PR TITLE
issue_69: Updated GNUPG cleanup method to ignored failed deletes (e.g…

### PR DESCRIPTION
**Pull request by jpl-jengelke**
…. file does not exist) to compensate for GNU PGP2 creating an intermittent concurrency issue when it cleans up the file itself during the call.

### CODE REVIEW

**Comment by jpl-jengelke** [comment]
Possible to get this into 1.2.8, please?

**Comment by jpl-jengelke** [comment]
Unfortunately, yes, it sometimes adds whitespace, claims it's a [PEP compliance issue](https://www.python.org/dev/peps/pep-0008/#blank-lines).

**Comment by jpl-jengelke** [comment]
I’ll wait for responses to 68, 69 to make changes.

**Comment by jpl-jengelke** [comment]
I removed the extra lines from the file in the branch, nothing else changes.

**Comment by al-niessner** [comment]
Closes #73

**Pull request merged**
