### PR TITLE
issue 7: FE updates

### LINKED ISSUE #7: front end improvements
Work being done by IPAC

### PR DESCRIPTION
**Pull request by al-niessner**
Closes #7

### CODE REVIEW

**Comment by al-niessner** [comment]
@jllamas you will need to fix check 4. Since I have docker installed, I do these steps:

```
.ci/step_00.sh
.ci/check_04.sh 1
git checkout .ci/status.txt
```

step_00 - builds the docker images that you need
check_04 - checks that all files have the appropriate legal text and if an argument is passed it will update the missing text but it always modifies .ci/status.txt
git checkout - cleans up dodo from check_04.

**Comment by al-niessner** [comment]
@jllamas Please remind me what the filters are supposed to like. I cannot find the email anymore so post the information here.

**Comment by al-niessner** [comment]
Filtering is giving me fits because I do not remember what we agreed to and it is not simple to guess. Here is what I am seeing:

## None (good)
none-good

## Admin (good)
### Filter
```
{
    "include":{".__metric__$":[]}
}
```
### Result
admin-good

### Summary
In this case note that only the __metric__ show up as desired.

## Dev (bad)
### Filter
```
{
    "exclude":[".__metric__$"],
}
```
### Result
dev-bad

### Summary
Notice that `__metric__` is still there despite the filter request to remove them.

## User (bad)
### Filter
```
{
    "include":{"cerberus.atmos.HST-WFC3-IR-G141-SCAN":[83,74,56],
               "cerberus.xslib.HST-WFC3-IR-G141-SCAN":[83,74,56]}
}
```

### Result
user-bad

### Summary
Notice from Dev or None that those state vectors do exist as do the run IDs. Therefore they should appear in the display.

**Comment by jllamas** [comment]
Hey Al,

Thats really strange and not the behavior I was seeing when I checked it in. Let me double check what I've done.

**Comment by jllamas** [comment]
Okay I was able to replicate your errors for Users and there was a bug that fixed. I could not replicate your dev errors. Here are the filters I tested against and the results on my box seem to match.

**None:**
None


**User**
```
{
    "include": {
      "^epe.orbit.": [12,11,5,1],
      ".hst_diff_accum.ima$": [14,13,11],
      "^calibrate.hst_stare_deconvolve.": [],
      "mcmclzz.syste_removal.ecl_ima": [],
      "makepriors.NBB.gen": [11,23]
    }
}
```
User


**Dev:**
```
{
    "exclude": {
      ".failed$": [],
      ".irrelevant$": [11],
      "filter.hst_spectra.irrelevant": [],
      "^calibrate.": []
    }
}
```
Dev


**Admin:**
```
{
    "include": {
      ".failed$": [],
      ".irrelevant$": [11],
      "^calibrate.": [],
      "activestar.visitnorm.raw": []
    }
}
```
Admin

**Comment by al-niessner** [comment]
My filter was bad. Thanks.

**Comment by markrswain** [comment]
Problem: If I go to the Database tab and enter a state vector or a target name, the buttons flash up for about 1/20 of a second and then vanish.

**Comment by markrswain** [comment]
"All Logs" button on main page does not take user to log messages

**Comment by markrswain** [comment]
FE purple selection indication feature is useful. Verified that it is linked to page and that multiple instances of Search Database page each keep their own purple maker. Passed test.

**Comment by markrswain** [comment]
About page: Run ID info *seems* ok. Sparse content likely due to @roudier

**Comment by al-niessner** [comment]
> Problem: If I go to the Database tab and enter a state vector or a target name, the buttons flash up for about 1/20 of a second and then vanish.

@markrswain  Filter has been fixed for Excalibur server and it works more less correctly now. Still flashes and may be empty if allowable state vectors do not exist for target.

@jllamas Can we have persistence on the User/Dev/Admin/None button so that it shows us our search based on the button we had selected. I noticed that when I reloaded the page, it set button to User.

**Comment by al-niessner** [comment]
> About page: Run ID info _seems_ ok. Sparse content likely due to @roudier

Yes, the paucity of information is the comment by commit author. In the next meeting what goes in the commit comment should be covered.

**Comment by al-niessner** [comment]
@jllamas 
__Question__: There is a new project using DAWGIE. Can you easily move EXCALIBUR and the front page image to files rather than embedded everywhere? It would be nice to swap a single file in fe somewhere that changed all of the EXCALIBURs to ETSs and replace the image with theirs.

**Comment by jpl-jengelke** [comment]
Thanks Al. Creating a templating dictionary to replace Excalibur and other application-specific text would be great. It would also be nice to have a way to turn on/off menus and/or add additional custom menus as needed.

**Comment by jllamas** [comment]
I'll work on the following today.

> **problem**: "All Logs" button on main page does not take user to log messages

> Can we have persistence on the User/Dev/Admin/None button so that it shows us our search based on the button we had selected. I noticed that when I reloaded the page, it set button to User.

> **Question**: There is a new project using DAWGIE. Can you easily move EXCALIBUR and the front page image to files rather than embedded everywhere? It would be nice to swap a single file in fe somewhere that changed all of the EXCALIBURs to ETSs and replace the image with theirs.

@al-niessner @markrswain
**Question**: While searching for State Vectors, the results are filtered the same as Name Search, however I'm removing all the rows for a given SV section (except the headers), is this what you guys want? Do we need to implement another set of filters or include a Target Names in the current filters?

**Comment by al-niessner** [comment]
> **Question**: While searching for State Vectors, the results are filtered the same as Name Search, however I'm removing all the rows for a given SV section (except the headers), is this what you guys want? Do we need to implement another set of filters or include a Target Names in the current filters? This way we can filter out individual rows as we do for TN search?

Not sure that I understand what you are asking. If an SV is excluded, it is for all targets. Hence, rows should be removed. Corollary for include is true too; meaning, rows not matching include should be removed.

**Comment by jllamas** [comment]
I've pushed the following changes to `issue_7`.

1 Changed the 'All Logs' button text to 'More Logs'. 
** It seems to correctly link to the `pages/logs` but the text implies 'All' which is incorrect, you just get 'More'
2 Added a browser cookie to store the Filter buttons active state. Now the button will remember across page loads. (but not sessions, browser restart)
3 Added the ability to rebrand the front end
** If `images/background.jpg` exists the site will load it into the home page background. Otherwise it will be black/gray.
** You must create a `javascripts/siteconfig.js` file for each deployment. This file will define text that should go in for the page title, navigation and header blocks.

Example of `javascripts/siteconfig.js` for Excalibur: 
```
var siteConfig = {
  site_title: "Excalibur",
  header_title: "Welcome to Excalibur",
  header_sub_title: "The <b>Ex</b>oplanet <b>Cali</b>bration <b>B</b>ayesian <b>U</b>nified <b>R</b>etrieval Pipeline",
  header_tag_line: "<em>The process is the product.</em>"
}
```
If `images/background.jpg` and `javascripts/siteconfig.js` don't exist, here is what the homepage will look like:
Screen Shot 2019-07-02 at 4 50 13 PM

**Comment by markrswain** [comment]
latest 9090 testing: Database tab, select "Trace Report" option on pulldown menu, get

Error: could not find static files /proj/src/front-end/pages/database/trace_report.html /usr/local/lib/python3.6/dist-packages/dawgie-1.2.2rc24-py3.6.egg/dawgie/fe/pages/database/trace_report.html

**Comment by markrswain** [comment]
Don't know what the yellow and mauve bars to the left of the various Pipeline Logs entries are suppose to indicate. These colors for some logs change when top buttons are selected.

**Comment by al-niessner** [comment]
> latest 9090 testing: Database tab, select "Trace Report" option on pulldown menu, get
> 
> Error: could not find static files /proj/src/front-end/pages/database/trace_report.html /usr/local/lib/python3.6/dist-packages/dawgie-1.2.2rc24-py3.6.egg/dawgie/fe/pages/database/trace_report.html

Expected. It requires the tool dawgie.tool.trace to be run to generate the file. I have not done this for 9090. Since we generate the page, lets ignore it for this PR.

**Comment by al-niessner** [comment]
> Don't know what the yellow and mauve bars to the left of the various Pipeline Logs entries are suppose to indicate. These colors for some logs change when top buttons are selected.

They indicate the level (warning - yellow, and mauve - critical). I am sure that error and info have their own colors as well but we do not have those kinds of log messages on 9090.

**Comment by jllamas** [comment]
> > Don't know what the yellow and mauve bars to the left of the various Pipeline Logs entries are suppose to indicate. These colors for some logs change when top buttons are selected.
> 
> They indicate the level (warning - yellow, and mauve - critical). I am sure that error and info have their own colors as well but we do not have those kinds of log messages on 9090.

Here is an example of the logs page with all the errors present. I've been out all this week

Screen Shot 2019-07-12 at 11 41 25 AM

**Pull request merged**
